# Generated by Django 5.1.7 on 2025-03-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kids',
            old_name='age',
            new_name='age_kid',
        ),
        migrations.RenameField(
            model_name='kids',
            old_name='email',
            new_name='email_kid',
        ),
    ]
